import { HttpClient } from "./http-client";

/** Acceptable classifications for Telentir managed phone numbers. */
export type PhoneNumberType = "inbound" | "outbound" | "both";

/** Telephony capabilities exposed by a phone number. */
export interface PhoneCapabilities {
  voice: boolean;
  sms: boolean;
  mms: boolean;
}

/** Provider specific reference metadata for a phone number. */
export interface PhoneReference {
  type: string;
  sid?: string;
  [key: string]: unknown;
}

/** Persisted phone number record. */
export interface PhoneNumberRecord {
  id: string;
  user_id: string;
  name: string;
  description: string | null;
  phone_number: string;
  type: PhoneNumberType;
  reference: PhoneReference;
  metadata?: {
    capabilities?: PhoneCapabilities;
    price?: {
      currency: string;
      amount: number;
    };
    [key: string]: unknown;
  };
  inbound_configuration_id?: string | null;
  created_at?: string;
  updated_at?: string;
}

/** Pricing quote embedded on phone search results. */
export interface PhoneNumberPriceQuote {
  currency: string;
  amount: number;
  jwt: string;
}

/** Search result structure returned from Twilio-backed discovery. */
export interface PhoneNumberSearchResult {
  name: string;
  phoneNumber: string;
  capabilities: PhoneCapabilities;
  addressRequirements: string | null;
  latitude: number | null;
  longitude: number | null;
  locality: string | null;
  price: PhoneNumberPriceQuote | null;
}

/** Country enumeration produced by the search endpoint. */
export interface PhoneNumberCountry {
  name: string;
  code: string;
  types: string[];
}

/** Payload accepted by `/api/phone-numbers` when purchasing a number. */
export interface PhoneNumberPurchaseInput {
  jwt: string;
  description?: string;
  addressSid?: string;
}

/** Twilio address requirements payload used for compliant purchasing. */
export interface PhoneNumberAddressInput {
  street: string;
  city: string;
  region: string;
  postalCode: string;
  isoCountry: string;
  friendlyName?: string;
  emergencyEnabled?: boolean;
  autoCorrectAddress?: boolean;
  streetSecondary?: string;
}

/** Query parameters accepted by the number search endpoint. */
export interface PhoneNumberSearchParams {
  country: string;
  type: string;
}

/**
 * Repository covering phone number listing, purchase and search flows.
 */
export class PhoneNumbersRepository {
  constructor(private readonly http: HttpClient) {}

  /** Lists all phone numbers owned by the current user. */
  async list(): Promise<PhoneNumberRecord[]> {
    return await this.http.request<PhoneNumberRecord[]>("/phone-numbers");
  }

  /** Fetches a single phone number record. */
  async get(id: string): Promise<PhoneNumberRecord> {
    return await this.http.request<PhoneNumberRecord>(`/phone-numbers/${id}`);
  }

  /**
   * Purchases and provisions a phone number through Telentir.
   *
   * @returns The created phone number identifier.
   */
  async purchase(input: PhoneNumberPurchaseInput): Promise<string> {
    const body: Record<string, unknown> = { jwt: input.jwt };
    if (input.description !== undefined) {
      body.description = input.description;
    }
    if (input.addressSid !== undefined) {
      body.addressSid = input.addressSid;
    }

    const response = await this.http.request<string>("/phone-numbers", {
      method: "PUT",
      headers: { "content-type": "application/json" },
      body: JSON.stringify(body),
    });

    return response;
  }

  /** Deletes a phone number and cancels associated subscriptions. */
  async delete(id: string): Promise<void> {
    await this.http.request(`/phone-numbers/${id}`, {
      method: "DELETE",
      responseType: "void",
    });
  }

  /**
   * Updates mutable metadata for a phone number (name, description).
   */
  async update(
    id: string,
    input: { name?: string; description?: string }
  ): Promise<PhoneNumberRecord> {
    return await this.http.request<PhoneNumberRecord>(`/phone-numbers/${id}`, {
      method: "PATCH",
      headers: { "content-type": "application/json" },
      body: JSON.stringify(input),
    });
  }

  /**
   * Saves a Twilio address SID or address details for compliance.
   *
   * @returns Address SID generated by Twilio.
   */
  async saveAddress(input: PhoneNumberAddressInput): Promise<string> {
    return await this.http.request<string>("/phone-numbers/address", {
      method: "PUT",
      headers: { "content-type": "application/json" },
      body: JSON.stringify(input),
    });
  }

  /** Returns supported phone number providers. */
  async listProviders(): Promise<string[]> {
    return await this.http.request<string[]>("/phone-numbers/search");
  }

  /**
   * Lists all supported countries for a given provider.
   */
  async listCountries(provider: string): Promise<PhoneNumberCountry[]> {
    return await this.http.request<PhoneNumberCountry[]>(
      `/phone-numbers/search/${provider}/countries`
    );
  }

  /**
   * Searches available phone numbers for the specified provider and filters.
   */
  async search(
    provider: string,
    params: PhoneNumberSearchParams
  ): Promise<PhoneNumberSearchResult[]> {
    return await this.http.request<PhoneNumberSearchResult[]>(
      `/phone-numbers/search/${provider}`,
      {
        query: {
          country: params.country,
          type: params.type,
        },
      }
    );
  }
}
